# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64bbbed5bd3b62748e7df30ae677ae7c3ba23bc4f653d84fc9e000d22ecdf8bbbcdc22e784b63c1ed218345232ccec3ae342d01592e05a63fa218bd0b2843e81

test:
  secret_key_base: da4cefd186701c90b6b7e2af34fe930dc3f2a5148958d370ef45fcf8953bc8987f8bf579ec6203f3adc00b4898352abb82605c4440951e1911dde4c693225948

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
